// Orchestrator - Central coordination for all agent modules
import { planner, type Task, type TaskStep } from './Planner';
import { memory } from './Memory';
import { verification } from './Verification';
import { toolRegistry } from './ToolRegistry';
import { capabilityRouter } from './CapabilityRouter';
import { policyEngine, type PolicyContext } from './PolicyEngine';
import { observationManager } from './ObservationLayer';
import { avatarStateMachine } from './AvatarStateMachine';

export type AgentState='idle'|'understanding'|'planning'|'observing'|'grounding'|'policy'|'acting'|'verifying'|'reflecting'|'complete'|'error';
export interface AgentEvent{type:string;state:AgentState;detail:string;timestamp:number;data?:any;}
export interface OrchestratorConfig{maxRetries:number;enableVerification:boolean;enableReflection:boolean;enableMemory:boolean;}

class Orchestrator{
 private state:AgentState='idle';private currentTask:Task|null=null;private eventLog:AgentEvent[]=[];private config:OrchestratorConfig={maxRetries:3,enableVerification:true,enableReflection:true,enableMemory:true};private listeners:((e:AgentEvent)=>void)[]=[];
 constructor(){this.loadConfig();}
 private loadConfig(){try{const s=localStorage.getItem('svetlana_orchestrator_config');if(s)this.config={...this.config,...JSON.parse(s)};}catch(e){console.error('Failed to load orchestrator config:',e);}}
 private saveConfig(){localStorage.setItem('svetlana_orchestrator_config',JSON.stringify(this.config));}
 on(l:(e:AgentEvent)=>void){this.listeners.push(l);return()=>{this.listeners=this.listeners.filter(x=>x!==l);};}
 private emit(e:Omit<AgentEvent,'timestamp'>){const x={...e,timestamp:Date.now()};this.eventLog.push(x);if(this.eventLog.length>1000)this.eventLog.shift();this.listeners.forEach(l=>l(x));}
 async execute(goal:string,context?:any){try{this.setState('understanding');this.emit({type:'understand',state:'understanding',detail:`Parsing goal: "${goal}"`,data:{goal}});if(this.config.enableMemory){memory.addMessage('user',goal);memory.addToShortTerm({type:'action',content:`User request: ${goal}`,importance:0.8});}this.setState('planning');this.emit({type:'plan',state:'planning',detail:'Planning with native LLM tool calling'});const task=await planner.createPlan({goal,context});this.currentTask=task;this.emit({type:'plan_complete',state:'planning',detail:`Created plan with ${task.steps.length} steps`,data:{task}});for(const step of task.steps){const r=await this.executeStep(step,context);if(!r.success){this.setState('error');this.emit({type:'error',state:'error',detail:`Step failed: ${step.action}`,data:{error:r.error}});return{success:false,error:r.error};}}this.setState('complete');this.emit({type:'complete',state:'complete',detail:'Task completed successfully'});if(this.config.enableMemory){memory.addMessage('assistant',`Task completed: ${goal}`);memory.addToLongTerm({type:'action',content:`Completed: ${goal}`,importance:0.6});}return{success:true,result:task};}catch(error:any){this.setState('error');this.emit({type:'error',state:'error',detail:error.message,data:{error:error.message}});return{success:false,error:error.message};}}
 private async executeStep(step:TaskStep,context?:any){this.setState('observing');avatarStateMachine.setExecuting();const observationResult=await observationManager.observe();const preState=observationResult.state;this.emit({type:'observe_result',state:'observing',detail:`Observation: ${observationResult.success?'SUCCESS':'FAILED'}`,data:{observation:observationResult}});this.setState('grounding');if(step.target)await observationManager.findElementByText(step.target);this.setState('policy');avatarStateMachine.setVerifying();const route=await capabilityRouter.resolve({action:step.action,parameters:step.parameters||{}});this.emit({type:'route',state:'policy',detail:route.success?`Routed ${step.action} -> ${route.tool!.id}`:`Routing failed: ${route.error}`,data:{route:{success:route.success,tool:route.tool?.id,backend:route.backend,candidates:route.candidates,error:route.error}}});if(!route.success||!route.tool)return{success:false,error:route.error||`No tool available for ${step.action}`};const tool=route.tool;const policyContext:PolicyContext={platform:observationManager.getContext().platform,currentApp:preState?.currentApp,environment:context||{}};const policyResult=await policyEngine.evaluate(tool,policyContext);this.emit({type:'policy',state:'policy',detail:`Policy: ${policyResult.decision} - ${policyResult.reason}`,data:{policy:policyResult}});if(policyResult.decision==='deny'){avatarStateMachine.setError();return{success:false,error:policyResult.reason};}if(policyResult.decision==='require_confirmation'){avatarStateMachine.setConfirmationRequired();return{success:false,error:'Requires user confirmation'};}this.setState('acting');const actionResult=await toolRegistry.executeTool(tool.id,step.parameters||{});this.emit({type:'act_result',state:'acting',detail:`Result: ${actionResult.success?'SUCCESS':'FAILED'}`,data:{result:actionResult}});if(!actionResult.success){avatarStateMachine.setError();planner.updateStepStatus(this.currentTask!.id,step.id,'failed',undefined,actionResult.error);return{success:false,error:actionResult.error};}policyEngine.recordSuccessfulExecution(tool.id);
 if(this.config.enableVerification){this.setState('verifying');const postObservation=await observationManager.observe();const postState=postObservation.state;const comparison=preState&&postState?observationManager.compareStates(preState,postState):{changed:false};const stateChanged=comparison.changed;const toolVerified=actionResult.verification?.status==='PASS';const independentCheck=toolVerified||stateChanged;this.emit({type:'verify_compare',state:'verifying',detail:`Independent check: ${independentCheck?'PASS':'PENDING'}`,data:{toolVerified,stateChanged,comparison}});const verificationResult=await verification.verify({action:step.action,expectedState:{success:true},actualState:actionResult});this.emit({type:'verify_result',state:'verifying',detail:`Contract verification: ${verificationResult.success?'PASS':'FAIL'}`,data:{verification:verificationResult}});
   if(!independentCheck){for(let retry=0;retry<this.config.maxRetries;retry++){this.emit({type:'retry',state:'verifying',detail:`Retry ${retry+1}/${this.config.maxRetries}`});await new Promise(r=>setTimeout(r,1000*Math.pow(2,retry)));const rr=await toolRegistry.executeTool(tool.id,step.parameters||{});if(!rr.success)continue;policyEngine.recordSuccessfulExecution(tool.id);const ro=await observationManager.observe();const retryChanged=!preState||!ro.state||observationManager.compareStates(preState,ro.state).changed;const retryVerified=rr.verification?.status==='PASS';if(retryVerified||retryChanged){avatarStateMachine.setSuccess();planner.updateStepStatus(this.currentTask!.id,step.id,'completed',rr);return{success:true};}}avatarStateMachine.setError();planner.updateStepStatus(this.currentTask!.id,step.id,'failed',undefined,'Independent verification failed after retries');return{success:false,error:'Independent verification failed after retries'};}
 }
 if(this.config.enableReflection){this.setState('reflecting');if(this.config.enableMemory)memory.addToLongTerm({type:'action',content:`Executed: ${tool.name} with params: ${JSON.stringify(step.parameters)}`,importance:0.6});}avatarStateMachine.setSuccess();planner.updateStepStatus(this.currentTask!.id,step.id,'completed',actionResult);return{success:true};}
 private setState(s:AgentState){this.state=s;} getState(){return this.state;}getCurrentTask(){return this.currentTask;}getEventLog(limit=50){return this.eventLog.slice(-limit);}getConfig(){return{...this.config};}updateConfig(u:Partial<OrchestratorConfig>){this.config={...this.config,...u};this.saveConfig();}reset(){this.state='idle';this.currentTask=null;}getStats(){return{state:this.state,totalEvents:this.eventLog.length,currentTask:this.currentTask?.id,memoryStats:memory.getStats(),verificationSuccessRate:verification.getSuccessRate()};}
}
export const orchestrator=new Orchestrator();
