// Tests for new tools: swipe, pressKey, goHome, goBack, searchWeb
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { toolRegistry } from '../services/ToolRegistry';
import { registerRealTools, swipeTool, pressKeyTool, goHomeTool, goBackTool, searchWebTool } from '../services/RealTools';
import { handsManager } from '../services/HandsManager';

describe('New Tools', () => {
  beforeEach(() => { vi.restoreAllMocks(); registerRealTools(); });

  describe('swipe tool', () => {
    it('should execute swipe successfully', async () => { const mockHands={isConnected:()=>true,swipe:vi.fn().mockResolvedValue({success:true})}; vi.spyOn(handsManager,'isConnected').mockResolvedValue(true); vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any); const result=await swipeTool.execute({startX:100,startY:500,endX:100,endY:200,duration:300}); expect(result.success).toBe(true); expect(result.data.startX).toBe(100); expect(result.data.endY).toBe(200); expect(mockHands.swipe).toHaveBeenCalledWith(100,500,100,200,300); });
    it('should handle swipe failure', async()=>{const mockHands={isConnected:()=>true,swipe:vi.fn().mockResolvedValue({success:false,error:'Swipe failed'})};vi.spyOn(handsManager,'isConnected').mockResolvedValue(true);vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any);const result=await swipeTool.execute({startX:100,startY:500,endX:100,endY:200});expect(result.success).toBe(false);expect(result.error).toContain('Swipe failed');});
  });
  describe('pressKey tool',()=>{it('should execute key press successfully',async()=>{const mockHands={isConnected:()=>true,pressKey:vi.fn().mockResolvedValue({success:true})};vi.spyOn(handsManager,'isConnected').mockResolvedValue(true);vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any);const result=await pressKeyTool.execute({key:'back'});expect(result.success).toBe(true);expect(result.data.key).toBe('back');expect(mockHands.pressKey).toHaveBeenCalledWith('back');});it('should handle key press failure',async()=>{const mockHands={isConnected:()=>true,pressKey:vi.fn().mockResolvedValue({success:false,error:'Key press failed'})};vi.spyOn(handsManager,'isConnected').mockResolvedValue(true);vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any);const result=await pressKeyTool.execute({key:'home'});expect(result.success).toBe(false);expect(result.error).toContain('Key press failed');});});
  describe('goHome tool',()=>{it('should navigate to home successfully',async()=>{const mockHands={isConnected:()=>true,goHome:vi.fn().mockResolvedValue({success:true}),getCurrentApp:vi.fn().mockResolvedValue('com.android.launcher')};vi.spyOn(handsManager,'isConnected').mockResolvedValue(true);vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any);const result=await goHomeTool.execute({});expect(result.success).toBe(true);expect(result.data.currentApp).toBe('com.android.launcher');expect(mockHands.goHome).toHaveBeenCalled();});it('should handle goHome failure',async()=>{const mockHands={isConnected:()=>true,goHome:vi.fn().mockResolvedValue({success:false,error:'Failed to go home'}),getCurrentApp:vi.fn()};vi.spyOn(handsManager,'isConnected').mockResolvedValue(true);vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any);const result=await goHomeTool.execute({});expect(result.success).toBe(false);expect(result.error).toContain('Failed to go home');expect(mockHands.getCurrentApp).not.toHaveBeenCalled();});});
  describe('goBack tool',()=>{it('should navigate back successfully',async()=>{const mockHands={isConnected:()=>true,goBack:vi.fn().mockResolvedValue({success:true}),getCurrentApp:vi.fn().mockResolvedValueOnce('com.app.settings').mockResolvedValueOnce('com.app.home')};vi.spyOn(handsManager,'isConnected').mockResolvedValue(true);vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any);const result=await goBackTool.execute({});expect(result.success).toBe(true);expect(result.data.beforeApp).toBe('com.app.settings');expect(result.data.afterApp).toBe('com.app.home');expect(result.data.navigated).toBe(true);expect(mockHands.goBack).toHaveBeenCalled();});it('should verify navigation occurred',async()=>{const mockHands={isConnected:()=>true,goBack:vi.fn().mockResolvedValue({success:true}),getCurrentApp:vi.fn().mockResolvedValueOnce('com.app.settings').mockResolvedValueOnce('com.app.home')};vi.spyOn(handsManager,'isConnected').mockResolvedValue(true);vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any);const result=await goBackTool.execute({});expect(await goBackTool.verify!({},result)).toBe(true);});it('should fail verification if no navigation occurred',async()=>{const mockHands={isConnected:()=>true,goBack:vi.fn().mockResolvedValue({success:true}),getCurrentApp:vi.fn().mockResolvedValueOnce('com.app.settings').mockResolvedValueOnce('com.app.settings')};vi.spyOn(handsManager,'isConnected').mockResolvedValue(true);vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any);const result=await goBackTool.execute({});expect(result.success).toBe(false);expect(await goBackTool.verify!({},result)).toBe(false);});});
  describe('searchWeb tool',()=>{it('should execute web search successfully',async()=>{const mockHands={isConnected:()=>true,launchApp:vi.fn().mockResolvedValue({success:true}),type:vi.fn().mockResolvedValue({success:true}),pressKey:vi.fn().mockResolvedValue({success:true})};vi.spyOn(handsManager,'isConnected').mockResolvedValue(true);vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any);const result=await searchWebTool.execute({query:'test query'});expect(result.success).toBe(true);expect(result.data.query).toBe('test query');expect(result.data.url).toContain('google.com/search');expect(result.data.browser).toBe('com.android.chrome');expect(mockHands.launchApp).toHaveBeenCalledWith('com.android.chrome');expect(mockHands.type).toHaveBeenCalled();expect(mockHands.pressKey).toHaveBeenCalledWith('enter');});it('should handle browser launch failure',async()=>{const mockHands={isConnected:()=>true,launchApp:vi.fn().mockResolvedValue({success:false,error:'Failed to open browser'})};vi.spyOn(handsManager,'isConnected').mockResolvedValue(true);vi.spyOn(handsManager,'getHands').mockReturnValue(mockHands as any);const result=await searchWebTool.execute({query:'test'});expect(result.success).toBe(false);expect(result.error).toContain('Failed to open browser');});});
  describe('Tool registration',()=>{it('should register all new tools',()=>{const ids=toolRegistry.getAllTools().map(t=>t.id);expect(ids).toContain('swipe');expect(ids).toContain('press_key');expect(ids).toContain('go_home');expect(ids).toContain('go_back');expect(ids).toContain('search_web');});it('should have correct risk levels',()=>{expect(toolRegistry.getTool('swipe')?.riskLevel).toBe('low');expect(toolRegistry.getTool('press_key')?.riskLevel).toBe('low');expect(toolRegistry.getTool('go_home')?.riskLevel).toBe('low');expect(toolRegistry.getTool('go_back')?.riskLevel).toBe('low');expect(toolRegistry.getTool('search_web')?.riskLevel).toBe('low');});it('should have correct categories',()=>{expect(toolRegistry.getTool('swipe')?.category).toBe('interaction');expect(toolRegistry.getTool('press_key')?.category).toBe('interaction');expect(toolRegistry.getTool('go_home')?.category).toBe('navigation');expect(toolRegistry.getTool('go_back')?.category).toBe('navigation');expect(toolRegistry.getTool('search_web')?.category).toBe('data');});});
});
